name: Obtenir i guardar temperatures diaries

on:
  workflow_dispatch:
  schedule:
    - cron: '59 21 * * *'  

jobs:
  obtenir_i_guardar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Instal·lar dependencies
        run: pip install requests  # Instalar llibreria requests
      - name: Executar el programa
        run: python temperatures.py
      - name: Pujar fitxer de dades
        uses: actions/upload-artifact@v3
        with:
          name: dades-temperatures
          path: temp_*.json
      - name: Commit i Push dels canvis
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Actualitza dades de temperatura diàries" || true # Ignora si no hi ha canvis
          git push origin main
